/**
* Copyright 2012-2019, Plotly, Inc.
* All rights reserved.
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*/


'use strict';

module.exports = {
    '0': '●',
    circle: '●',
    '100': '○',
    'circle-open': '○',
    '300': '⊙',
    'circle-open-dot': '⊙',
    '1': '■',
    square: '■',
    '101': '□',
    'square-open': '□',
    '2': '◆',
    diamond: '◆',
    '102': '◇',
    'diamond-open': '◇',
    '302': '⟐',
    'diamond-open-dot': '⟐',
    '3': '+',
    cross: '+',
    '4': '❌',
    x: '❌',
    '5': '▲',
    'triangle-up': '▲',
    '105': '△',
    'triangle-up-open': '△',
    '305': '◬',
    'triangle-up-open-dot': '◬',
    '6': '▼',
    'triangle-down': '▼',
    '106': '▽',
    'triangle-down-open': '▽',
    '7': '◀',
    'triangle-left': '◀',
    '107': '◁',
    'triangle-left-open': '◁',
    '8': '▶',
    'triangle-right': '▶',
    '108': '▷',
    'triangle-right-open': '▷',
    '9': '◥',
    'triangle-ne': '◥',
    '109': '◹',
    'triangle-ne-open': '◹',
    '10': '◢',
    'triangle-se': '◢',
    '110': '◿',
    'triangle-se-open': '◿',
    '11': '◣',
    'triangle-sw': '◣',
    '111': '◺',
    'triangle-sw-open': '◺',
    '12': '◤',
    'triangle-nw': '◤',
    '112': '◸',
    'triangle-nw-open': '◸',
    '13': '⬟',
    'pentagon': '⬟',
    '113': '⬠',
    'pentagon-open': '⬠',
    '14': '⬢',
    'hexagon': '⬢',
    '114': '⬡',
    'hexagon-open': '⬡',
    '15': '⬣',
    'hexagon2': '⬣',
    '16': '⯃',
    'octagon': '⯃',
    '17': '★',
    'star': '★',
    '18': '🟌',
    'hexagram': '🟌',
    '25': '⧗',
    'hourglass': '⧗',
    '125': '⧖',
    'hourglass-open': '⧖',
    '26': '⧓',
    'bowtie': '⧓',
    '126': '⋈',
    'bowtie-open': '⋈',
    '127': '⊕',
    'circle-cross-open': '⊕',
    '128': '⊗',
    'circle-x-open': '⊗',
    '129': '⊞',
    'square-cross-open': '⊞',
    '130': '⊠',
    'square-x-open': '⊠',
};
